name: 'run_user_tests'

on:
  workflow_dispatch:
  
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday

  workflow_call:  

jobs:
  user-tests:
    name: Test-${{ matrix.user_name }}/${{ matrix.repo_name }}
    strategy:
      fail-fast: false
      matrix: 
        include:
          - { user_name: ess-dg, repo_name: dgcode_projects} 
          #add user repositories here
          
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.allow-failure == 1 }} 
    defaults:
      run:
        shell: bash
    env:
      SHELL: /bin/bash
      CC: gcc-10
      CXX: g++-10
      PROJECTS_DIR: projects
      BUILD_FLAG: examine

    steps:
      - name: Checkout dgcode_actions
        uses: actions/checkout@v3
        with:
          repository: mctools/dgcode_actions

      - name: Checkout ${{ matrix.user_name }}/${{ matrix.repo_name }}
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.user_name }}/${{ matrix.repo_name }}
          path: './packages'

      - name: setup framework action
        id: setup-framework
        uses: ./.github/actions/setup
        with:
          PYTHON_VERSION: '3.9'
          PROJECTS_DIR: ${{ env.PROJECTS_DIR }}
          DGBUILD_FLAG: ${{ env.BUILD_FLAG }}
         
      - name: Run tests
        run: |
          . $GITHUB_WORKSPACE/dgdepfixerInstall/setup.sh
          export DGCODE_PKG_PATH="$GITHUB_WORKSPACE/packages"
          . bootstrap.sh
          dgbuild -at --testexcerpts=20 --${{ env.BUILD_FLAG }}
        working-directory: ${{ env.PROJECTS_DIR }}
        env:
          DGDEP_IGNOREBADSHEBANG: 1

      - name: Rename test result
        id: rename-test-result
        if: always() && steps.setup-framework.outcome == 'success'
        run: mv $GITHUB_WORKSPACE/${{ env.PROJECTS_DIR }}/.bld/testresults/dgtest_results_junitformat.xml $GITHUB_WORKSPACE/${{ env.PROJECTS_DIR }}/.bld/testresults/dgtest_results_junitformat_${{ matrix.user_name }}_${{ matrix.repo_name }}.xml

      - uses: actions/upload-artifact@v2  # upload test results
        if: always() && steps.rename-test-result.outcome == 'success'
        with:
          name: test-results-user-tests
          path: ${{ github.workspace }}/${{ env.PROJECTS_DIR }}/.bld/testresults/dgtest_results_junitformat_${{ matrix.user_name }}_${{ matrix.repo_name }}.xml

  report:
    name: Test reporting
    if: always()
    needs: user-tests
    runs-on: ubuntu-latest
    steps:

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results-user-tests
        path: artifact_dir

    # - name: Publish Test Report
    #   uses: mikepenz/action-junit-report@v3
    #   if: always() # run even if the previous step fails
    #   with:
    #     check_name: User Tests Report (mikepenz)
    #     report_paths: artifact_dir/dgtest_results_junitformat*.xml
  
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        check_name: User Tests Report (EnricoMi)
        files: artifact_dir/dgtest_results_junitformat*.xml
        report_individual_runs: "true"
        comment_mode: "off" #control pull request comments